### ISSUE TITLE
Add class names to expose library elements for CSS styling

### ISSUE THREAD

**Issue by nishanbajracharya** [nishanbajracharya/react-virtualized-listview#1]
Add class names to the DOM elements in the `src/index.js` file.
A namespaced classname like `React_Virtualized_Listview__classname` is preferred.

Eg:
```jsx
<div style={style.container} ref={c => (this.container = c)} className="React_Virtualized_Listview__container">
```

**Comment by rabingaire20** [comment]
I would love to help with this.

**Comment by rabingaire20** [comment]
And I was thinking about this and would not it be easier to do something like this 

```javascript
const data = [1, 2, 3, 4, 5];

<List
  source={data}
  rowHeight={40}
  className="<my_class_name>"
  renderItem={({ index, style }) => (
    <div key={index} style={style}>
      Hello {index}
    </div>
  )}
/>
```
and override the classname underneath the library
Just a thought though.

**Comment by nishanbajracharya** [comment]
The first part will be to have a default library specific classname and next would be a custom classname that the developer can add to override the default.
```js
<List
  className="my-class-name" />
```

And somewhere in the library, the provided classname would be appended.
```js
<div className={`React_Virtualized_Listview__list_window ${this.props.className}`} />
```

The idea is the developer can either add styles to the default namespace provided or use a custom classname as they like.

**Comment by rabingaire** [comment]
I will work on this today.
